### ISSUE TITLE
3.1 Create exit game functionality

### ISSUE THREAD

**Issue by dllm-pk** [dllm-pk/ETI_Team02_assignment1#5]
(Victor)

**Comment by Faris122** [comment]
This needs to be redone with evidence of TDD, use mainprog.py not full_program.py

**Comment by Faris122** [comment]
Please update me on the progress, this has to be developed with TDD

**Comment by Faris122** [comment]
@enrypoint22 dont need to do this, do Bing Chong's #7 instead
